### PR TITLE
add an additional if clause for done

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
I'm not sure if this makes sense. I will lean on you guys to let me know if it does. If it does in fact, great. If not, we can kill it. I'm not sure I know what the bug is that the relevant commit was addressing.

### CODE REVIEW

**Comment by kordless** [comment]
Code style changes aside, this code fails to run in a local development environment:

```
Sidekick:buttons kord$ make serve
dev_appserver.py --enable_console --host=0.0.0.0 --port=8079 --admin_host=0.0.0.0 --admin_port=8088 ./
INFO     2019-04-12 19:57:52,193 devappserver2.py:278] Skipping SDK update check.
INFO     2019-04-12 19:57:52,783 api_server.py:275] Starting API server at: http://localhost:62551
INFO     2019-04-12 19:57:52,930 dispatcher.py:256] Starting module "default" running at: http://0.0.0.0:8079
INFO     2019-04-12 19:57:52,939 admin_server.py:150] Starting admin server at: http://0.0.0.0:8088
INFO     2019-04-12 19:57:55,120 instance.py:294] Instance PID: 6253
ERROR    2019-04-12 19:57:56,842 wsgi.py:263]
Traceback (most recent call last):
  File "/Users/kord/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/kord/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/kord/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/kord/Code/streams/projects/buttons/main.py", line 37, in <module>
    import routes
  File "/Users/kord/Code/streams/projects/buttons/routes.py", line 2, in <module>
    from web.handlers import sitehandlers, adminhandlers, userhandlers, instancehandlers, emailhandlers
  File "/Users/kord/Code/streams/projects/buttons/web/handlers/instancehandlers.py", line 249
    if json.loads(content)['status'] == "PENDING"
                                                 ^
SyntaxError: invalid syntax
INFO     2019-04-12 19:57:56,849 module.py:861] default: "GET /_ah/warmup HTTP/1.1" 500 -
```

Given the duplication of code and the fact the internal responses are to the cron.yaml call only, I might suggest a review of the reasons for this pull request.

**Comment by MarcusSorealheis** [comment]
that's right
I was not commenting on style, I was commenting on why are provisioning and done treated the same?

**Comment by MarcusSorealheis** [comment]
I'm asking specifically because of some instances being killed

**Comment by MarcusSorealheis** [comment]
Instances appeared to be related to quota alone

**Pull request closed without merging**
